nginx:
  build: "."
  container_name: server-container
  restart: always
  volumes:
    - ./php:/var/www/html
    - ./nginx/sites-available:/etc/nginx/sites-available
  ports:
    - "80:80"
    - "443:443"
  links:
    - memcached
    - mysql
    - redis
mysql:
  image: mysql:8.0.1
  command: --default-authentication-plugin=mysql_native_password
  container_name: mysql-container
  environment: 
    MYSQL_ROOT_PASSWORD: F@CILITA
  volumes:
    - ./data:/var/lib/mysql
  restart: always
memcached:
  image: sameersbn/memcached:1.5.6-2
  container_name: memcached-container
  ports:
    - "11211:11211"
  restart: always
redis:
  image: redis