version: "3.7"
services:
  db:
    image: mysql:8.0.1
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
  api:
    build: "./api"
    container_name: node-container
    restart: always
    volumes:
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db
  web:
    image: "php-image:7.0"
    container_name: php-container
    restart: always
    volumes: 
      - ./php/website:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
      - api