version: '3'
services:
  web:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./data/php:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - ./data/logs/Nginx:/var/log/nginx
    networks:
      nginxphp:
        ipv4_address: 172.28.1.1

  php:
    container_name: php
    # build: PHP
    image: dennylsoncosta/php70-memcached
    # command: service memcached start
    volumes:
      - ./data/php:/public_html
    expose:
      - 9000
    networks:
      nginxphp:
        ipv4_address: 172.28.1.2

  mysql:
    container_name: mysql
    image: mysql:8.0.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=F@CILITA
      - MYSQL_DATABASE=dennylson_ajustes
    volumes:
    -   ./data/db:/var/lib/mysql
    networks:
      nginxphp:
        ipv4_address: 172.28.1.3

networks: 
  nginxphp:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16